http:
  middlewares:
    keycloak-set-https:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Host: {{ env "KEYCLOAK_HOST" }}
          X-Forwarded-Port: "443"

  routers:
    keycloak:
      rule: Host(`{{ env "KEYCLOAK_HOST" }}`)
      service: keycloak-svc
      entryPoints: [web]
      middlewares:
        - keycloak-set-https

  services:
    keycloak-svc:
      loadBalancer:
        servers:
          - url: 'http://{{ env "KEYCLOAK_IP" }}:{{ env "KEYCLOAK_PORT" }}'
