http:
  routers:
    uptime:
      rule: "Host(`{{ env \"UPTIME_HOST\" }}`)"
      service: uptime-svc
      entryPoints: [web]

  services:
    uptime-svc:
      loadBalancer:
        servers:
          - url: "http://{{ env \"UPTIME_IP\" }}:{{ env \"UPTIME_PORT\" }}"
