version: '3'

services:
  bjn_nginx:
    image: briannunez/nginx-main:${X_BJN_NGINX_VERSION}
    container_name: bjn-nginx-server
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80
    environment:
      - host=${X_NGINX_HOST}
      - port=${HTTP_PORT}
