version: '3'

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - ${X_MINIO_API_PORT}:9000
      - ${X_MINIO_BROWSER_PORT}:9001
    volumes:
      - ${X_MINIO_VOLUME_PATH}:/data
    environment:
      MINIO_ROOT_USER=${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":${X_MINIO_BROWSER_PORT}"
