services:
  forgejo:
    image: ${FORGEJO_IMAGE}
    container_name: ${FORGEJO_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${FORGEJO_DOCKER_PORT}:${FORGEJO__server__HTTP_PORT}"
    environment:
      - USER_UID=${USER_UID:-1000}
      - USER_GID=${USER_GID:-1000}
      - FORGEJO__server__ROOT_URL=${FORGEJO__server__ROOT_URL}
      - FORGEJO__server__DOMAIN=${FORGEJO__server__DOMAIN}
      - FORGEJO__server__SSH_DOMAIN=${FORGEJO__server__SSH_DOMAIN}
      - FORGEJO__server__PROTOCOL=${FORGEJO__server__PROTOCOL}
      - FORGEJO__server__HTTP_PORT=${FORGEJO__server__HTTP_PORT}
      - FORGEJO__database__DB_TYPE=${FORGEJO__database__DB_TYPE}
    env_file:
      - .env
    volumes:
      - ${FORGEJO_VOLUME_PATH}:/data
      - ${FORGEJO_TIMEZONE_PATH}:/etc/timezone:ro
      - ${FORGEJO_LOCALETIME_PATH}:/etc/localtime:ro
