services:
  keycloak:
    image: ${KEYCLOAK_IMAGE}
    container_name: ${KEYCLOAK_CONTAINER_NAME}
    command: start
    restart: unless-stopped
    environment:
      - KC_HEALTH_ENABLED=${KC_HEALTH_ENABLED}
      - KC_METRICS_ENABLED=${KC_METRICS_ENABLED}
      - KC_HTTP_ENABLED=${KC_HTTP_ENABLED}
      - KC_PROXY=${KC_PROXY}
      - KC_HOSTNAME_STRICT_HTTPS=${KC_HOSTNAME_STRICT_HTTPS}
      - KC_HOSTNAME_STRICT_BACKCHANNEL=${KC_HOSTNAME_STRICT_BACKCHANNEL}
      - KC_HOSTNAME_STRICT=${KC_HOSTNAME_STRICT}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KEYCLOAK_FRONTEND_URL=${KEYCLOAK_FRONTEND_URL}
      - DB_VENDOR=${DB_VENDOR}
      - DB_ADDR=${DB_ADDR}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "${KEYCLOAK_DOCKER_PORT:-9090}:8080"

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
    restart: unless-stopped

